### ISSUE TITLE
Importing SpectralFitterPgstat from gdt.core.spectra.fitting raises an error as scipy.misc.derivative has been removed from Scipy 1.12.0

### ISSUE THREAD

**Issue by dhruvsbal** [USRA-STI/gdt-core#87]
Hi! I installed Gamma-ray Data tools on March 16th, 2025 on Ubuntu 24.04. The version of Python is 3.12. and scipy is 1.14.0. I was trying to follow the Jupyter Notebook tutorial- "Spectral Analysis Tutorial" for fitting spectral data from GBM for a GRB. All steps before the "from gdt.core.spectra.fitting import SpectralFitterPgstat" cell worked perfectly. However, importing SpectralFitterPgstat raised an error as the scipy.misc.derivative has been removed from SciPy 1.12.0. 

The error was as follows: "cannot import name 'derivative' from 'scipy.misc' ". 

Scipy recommends using the following alternatives: "https://github.com/maroba/findiff/" or "https://github.com/pbrod/numdifftools". One of these alternatives or something similar may need to be updated in "SpectralFitterPgstat" instead of scipy.misc.derivative otherwise "SpectralFitterPgstat" will not work for scipy>= 1.12.0. 

Please let me know if you require any other information from me!

**Comment by JamesAmrhein** [comment]
You can use get-fermi's Spectral_Analysis_Tutorial as a test case for this issue:
https://github.com/USRA-STI/gdt-fermi/blob/main/docs/notebooks/Spectral_Analysis_Tutorial.ipynb.tar

**Comment by joshuarwood** [comment]
Can you try re-installing the latest main branches for gdt-core and gdt-fermi?

We pushed a change yesterday that replaces scipy.misc.derivative with a derivative method defined within gdt. We can close the issue if it fixes your scipy dependency issues.

Minor side note - scipy.misc.derivative was intended to be removed in scipy 1.12.0 but it should be present up to 14.1. It's present in the documentation for scipy version 1.14.1 (along with the out-dated deprecation message):
https://docs.scipy.org/doc/scipy-1.14.1/reference/generated/scipy.misc.derivative.html#scipy.misc.derivative

I tested that scipy versions 1.14.0 and 1.14.1 work with our older code in python3.11 on a 2023 macbook.

Scipy >=1.15.0 is known to have removed all functions in scipy.misc.

**Comment by AdamGoldstein-USRA** [comment]
This was fixed in PR #90
